'use strict';
const {products,money,lines,total,amount,validate,change}=POS;
let cart={},screen='order',category='All',cash='',transaction=null,busy=false,noticeTimer;
const app=document.querySelector('#app');
const paths={coffee:'M16 23h27v20a12 12 0 0 1-12 12h-3a12 12 0 0 1-12-12z M43 27h5a7 7 0 0 1 0 14h-5 M25 10v7 M34 10v7',sandwich:'M9 46 32 15 55 46v9H9z M15 39h34 M9 46h46',soda:'M18 26h30l-4 31H22z M32 26l7-17h9 M20 37h26',cookies:'M55 33a23 23 0 1 1-46 0 23 23 0 0 1 46 0 M23 25h1 M39 22h1 M29 39h1 M43 40h1 M20 43h1',water:'M27 8h10v9l6 9v29a5 5 0 0 1-5 5H26a5 5 0 0 1-5-5V26l6-9z M22 35h20 M22 46h20',chocolate:'M20 9h24a5 5 0 0 1 5 5v41a5 5 0 0 1-5 5H20a5 5 0 0 1-5-5V14a5 5 0 0 1 5-5 M32 10v49 M16 26h32 M16 43h32',cash:'M8 18h48v30H8z M39 33a7 7 0 1 1-14 0 7 7 0 0 1 14 0',qr:'M9 9h17v17H9z M38 9h17v17H38z M9 38h17v17H9z M38 38h8v8h9v9H38z',card:'M8 15h48v36H8z M8 25h48 M16 40h10',bag:'M15 20h34l4 37H11z M24 20v-6a8 8 0 0 1 16 0v6'};
function icon(id){return `<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[id]||paths.bag}"/></svg>`;}
function button(label,action,cls='',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function notify(message){clearTimeout(noticeTimer);document.querySelector('#notice').textContent=message;noticeTimer=setTimeout(()=>document.querySelector('#notice').textContent='',3200);}
function go(next){if(busy)return;if(!total(cart)&&!['order','receipt','success'].includes(next))return;screen=next;render();window.scrollTo(0,0);app.querySelector('h1')?.focus({preventScroll:true});}
function orderTable(items){return `<div class="table-wrap"><table><caption class="sr-only">Selected products, quantities, unit prices and subtotals</caption><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th><th>Subtotal</th></tr></thead><tbody>${items.map(p=>`<tr><td><span class="review-product"><span class="review-icon">${icon(p.id)}</span><span><strong>${p.name}</strong><small>${p.category}</small></span></span></td><td>${p.quantity}</td><td>${money(p.price)}</td><td>${money(p.subtotal)}</td></tr>`).join('')}</tbody></table></div>`;}
function details(t){return `<dl><div><dt>Transaction No.</dt><dd class="reference">${t.id}</dd></div><div><dt>Payment method</dt><dd>${t.method}</dd></div><div><dt>Transaction amount</dt><dd>${money(t.total)}</dd></div><div><dt>Amount paid</dt><dd>${money(t.paid)}</dd></div><div><dt>Change</dt><dd>${money(t.change)}</dd></div></dl>`;}
function render(){
 const items=lines(cart),due=total(cart),count=items.reduce((n,p)=>n+p.quantity,0),step=screen==='order'?0:screen==='review'?1:['success','receipt'].includes(screen)?3:2;
 document.querySelector('#progress').innerHTML=['Order','Review','Payment','Receipt'].map((s,i)=>`<span class="${i===step?'active':i<step?'done':''}" ${i===step?'aria-current="step"':''}>${i<step?'✓':i+1} ${s}</span>`).join('');
 if(screen==='order')app.innerHTML=`<div class="order-layout"><section class="catalog"><div class="catalog-head"><div class="intro"><span class="eyebrow">THE CAMPUS EDIT</span><h1 tabindex="-1">Your next break<br>starts here.</h1><p>Choose a favorite. Tap again to add another.</p></div><div class="filters" aria-label="Product categories">${['All','Drinks','Food','Snacks'].map(c=>button(c,'filter',category===c?'selected':'',`data-category="${c}" aria-pressed="${category===c}"`)).join('')}</div></div><div class="menu-heading"><h2>Find your favorite</h2><span>${products.filter(p=>category==='All'||p.category===category).length} favorites · ${category}</span></div><div class="products">${products.filter(p=>category==='All'||p.category===category).map(p=>`<button class="product ${p.id} ${cart[p.id]?'chosen':''}" data-action="add" data-id="${p.id}" aria-label="Add ${p.name}, ${money(p.price)}, ${cart[p.id]||0} in your order">${cart[p.id]?`<span class="badge">✓ ${cart[p.id]} in bag</span>`:''}<div class="art"><span class="art-orbit"></span>${icon(p.id)}<span class="add-mark" aria-hidden="true">+</span></div><div class="product-meta"><div><small class="product-category">${p.category}</small><strong>${p.name}</strong></div><strong class="price">${money(p.price)}</strong></div></button>`).join('')}</div></section><aside class="cart" aria-label="Current order"><div class="row"><h2>Your bag<span class="heading-dot">.</span></h2><span class="muted">${count} ${count===1?'item':'items'}</span></div><div class="cart-items">${items.length?items.map(p=>`<div class="cart-item"><div class="row"><div><strong>${p.name}</strong><small>${money(p.price)} each</small></div>${button('Remove','remove','remove',`data-id="${p.id}" aria-label="Remove ${p.name}"`)}</div><div class="qty">${button('−','minus','',`data-id="${p.id}" aria-label="Decrease ${p.name}"`)}<strong>${p.quantity}</strong>${button('+','add','',`data-id="${p.id}" aria-label="Increase ${p.name}"`)}<strong class="subtotal">${money(p.subtotal)}</strong></div></div>`).join(''):`<div class="empty">${icon('bag')}<h3>Your order is empty</h3><p>Good things start with a little something. Tap a favorite to get started.</p></div>`}</div><div class="row total"><span>Total</span><strong data-testid="total">${money(due)}</strong></div>${button('Review your order ↗','review','primary wide',!items.length?'disabled':'')}</aside></div>`;
 if(screen==='review')app.innerHTML=`<section class="panel review-panel"><span class="eyebrow">ONE LAST LOOK</span><h1 tabindex="-1">Review your order</h1><p>Everything look right? Go back anytime to adjust your items.</p>${orderTable(items)}<div class="total row"><div>Order total<small class="muted" style="display:block;font-size:15px;margin-top:8px">${count} items</small></div><strong>${money(due)}</strong></div><div class="actions">${button('← Back','order')}${button('Continue to Payment →','methods','primary')}</div></section>`;
 if(['methods','cash','qr','card'].includes(screen)){
  const selected=screen!=='methods',locked=busy?'disabled':'',titles={cash:'Cash Payment',qr:'QR Payment',card:'Credit / Debit Card'};
  let content='';
  if(screen==='cash')content=`<div class="cash-layout"><div><label for="cash">Amount paid</label><input id="cash" class="cash-input" inputmode="decimal" autocomplete="off" placeholder="&#8369;0.00" aria-describedby="cash-hint cash-error" maxlength="10" ${locked}><p id="cash-hint">Enter cash received or choose a quick amount.</p><div class="quick">${[['Exact',due/100],['\u20b1200',200],['\u20b1500',500],['\u20b11,000',1000]].map(([s,v])=>button(s,'quick','',`data-value="${v}" ${locked}`)).join('')}</div><p id="cash-error" class="error" role="alert"></p><div class="change row" aria-live="polite"><span>Change to return</span><strong id="change">&mdash;</strong></div></div><div><div class="keypad" aria-label="Cash amount keypad">${['1','2','3','4','5','6','7','8','9','.','0','\u232b'].map(n=>button(n,'key','',`data-value="${n}" aria-label="${n==='\u232b'?'Backspace':n==='.'?'Decimal point':n}" ${locked}`)).join('')}</div>${button('Clear amount','clear','wide',locked)}</div></div>${button(busy?'Processing...':'Pay Now','pay','primary wide',locked)}`;
  if(screen==='qr')content=`<div class="payment-device-layout"><div class="qr-placeholder">${icon('qr')}<strong>Demo QR</strong><span>Placeholder &middot; not scannable</span></div><div><h2>Pay with your e-wallet</h2><p>A real kiosk would show a QR code here. For this demo, tap Confirm Payment to simulate approval.</p><p>The exact amount due is recorded, with no change.</p>${button(busy?'Confirming...':'Confirm Payment','confirm','primary wide',locked)}</div></div>`;
  if(screen==='card')content=`<div class="payment-device-layout"><div class="card-reader">${icon('card')}<strong>${busy?'Reading payment...':'Ready for your card'}</strong><span>Tap &middot; insert &middot; swipe</span><div class="reader-slot" aria-hidden="true"></div></div><div><h2>Card reader simulation</h2><p>Tap Process Payment to simulate a card approval. No card or card details are needed.</p><p>The exact amount due is recorded, with no change.</p>${button(busy?'Processing...':'Process Payment','process','primary wide',locked)}</div></div>`;
  app.innerHTML=`<section class="panel payment-panel"><div class="payment-heading"><div><span class="eyebrow">THE FINAL STEP</span><h1 tabindex="-1">${selected?titles[screen]:'How would you like to pay?'}</h1><p>${selected?'Your payment method is selected below.':'Choose a payment method to finish your order.'}</p></div><div class="due"><small>Amount due</small><strong>${money(due)}</strong><span>${count} ${count===1?'item':'items'} in your order</span></div></div><div class="methods" role="group" aria-label="Payment method">${[['cash','Cash','Cash received & change'],['qr','QR Payment','E-wallet simulation'],['card','Credit / Debit Card','Card reader simulation']].map(([id,title,desc])=>`<button class="method ${screen===id?'is-selected':''}" data-action="${id}" aria-pressed="${screen===id}" ${locked}>${icon(id)}<span class="method-state">${screen===id?'Selected':'Choose'}</span><strong>${title}</strong><span class="method-description">${desc}</span></button>`).join('')}</div>${selected?`<div class="payment-content" aria-busy="${busy}">${content}</div>`:''}<div class="payment-status" role="status" aria-live="polite">${busy?'<span class="spinner" aria-hidden="true"></span>Processing simulated payment. Please wait...':''}</div><div class="actions payment-navigation">${button('&larr; Back to Review','review','',locked)}${selected?button('Change Payment Method','methods','',locked):''}</div><p class="simulation">Demonstration kiosk &middot; No real payment is collected.</p></section>`;
  if(screen==='cash'){document.querySelector('#cash').value=cash;updateCash();}
 }
 if(screen==='success')app.innerHTML=`<section class="panel narrow success"><div class="check">✓</div><h1 tabindex="-1">Payment Successful</h1><p>Transaction completed successfully. Thank you!</p>${details(transaction)}${button('View Receipt','receipt','primary wide')}</section>`;
 if(screen==='receipt'){const t=transaction;app.innerHTML=`<div class="receipt-layout"><section class="receipt"><h2>CAMPUS STORE POS</h2><p>Self-Service Kiosk · Digital Receipt</p><dl><div><dt>Transaction No.</dt><dd class="reference">${t.id}</dd></div><div><dt>Date</dt><dd>${new Intl.DateTimeFormat('en-PH',{dateStyle:'long',timeStyle:'short',timeZone:'Asia/Manila'}).format(new Date(t.date))} (PHT)</dd></div></dl><table><thead><tr><th>Item</th><th>Subtotal</th></tr></thead><tbody>${t.items.map(p=>`<tr><td>${p.name}<small>${p.quantity} × ${money(p.price)}</small></td><td>${money(p.subtotal)}</td></tr>`).join('')}</tbody></table><div class="total row"><span>TOTAL</span><strong>${money(t.total)}</strong></div><dl><div><dt>Payment method</dt><dd>${t.method}</dd></div><div><dt>Amount paid</dt><dd>${money(t.paid)}</dd></div><div><dt>Change</dt><dd>${money(t.change)}</dd></div><div><dt>Status</dt><dd>Payment Successful</dd></div></dl><p>Thank you for your purchase!</p></section><section class="receipt-actions"><h1 tabindex="-1">Your receipt</h1><p>Keep this for your records. Tap New Transaction when you are done — your order and payment details will be cleared.</p>${button('New Transaction','reset','primary')}${button('Print Receipt','print')}<p class="simulation">Printing is optional. Payments in this kiosk are simulated.</p></section></div>`;}
}
function updateCash(submitted=false){
 const field=document.querySelector('#cash');if(!field)return;
 const paid=amount(cash),due=total(cart),result=validate(cash,due);
 const error=(submitted||cash!=='')?result.error||'':'';
 document.querySelector('#change').textContent=paid!==null&&paid>=due?money(paid-due):'\u2014';
 document.querySelector('#cash-error').textContent=error;
 field.setAttribute('aria-invalid',String(Boolean(error)));
}
function simulate(method,paid){
 if(busy||transaction||!total(cart))return;
 busy=true;render();
 setTimeout(()=>complete(method,paid),1400);
}
function complete(method,paid){if(transaction||!total(cart))return;transaction={id:'TXN-'+crypto.randomUUID().toUpperCase(),date:new Date().toISOString(),items:lines(cart),total:total(cart),method,paid,change:paid-total(cart)};busy=false;go('success');notify('Transaction completed successfully');}
app.addEventListener('input',e=>{if(e.target.id==='cash'&&!busy){cash=e.target.value;updateCash();}});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||busy)return;const a=b.dataset.action,id=b.dataset.id;
 if(['add','minus','remove'].includes(a)){
  const p=products.find(p=>p.id===id),fromProduct=b.classList.contains('product'),previous=cart[id]||0;
  if(a==='remove'){delete cart[id];}
  else{if(a==='add'&&previous>=99){notify('Maximum quantity is 99 per product');return;}cart=change(cart,id,a==='add'?1:-1);}
  const quantity=cart[id]||0;
  notify(!quantity?`${p.name} removed`:!previous?`${p.name} added to your order`:`${p.name} quantity: ${quantity}`);
  const listScroll=app.querySelector('.cart-items').scrollTop;
  render();
  app.querySelector('.cart-items').scrollTop=listScroll;
  const scope=fromProduct?'.products':'.cart-items';
  const target=app.querySelector(`${scope} [data-action="${a}"][data-id="${id}"]`)
   ||app.querySelector(`.product[data-id="${id}"]`)||app.querySelector('.filters .selected');
  target?.focus({preventScroll:true});return;
 }
 if(a==='filter'){category=b.dataset.category;render();app.querySelector('.filters .selected')?.focus({preventScroll:true});return;}
 if(['quick','key','clear'].includes(a)){if(a==='quick')cash=b.dataset.value;else if(a==='clear')cash='';else if(b.dataset.value==='⌫')cash=cash.slice(0,-1);else if(b.dataset.value==='.')cash=cash.includes('.')?cash:(cash||'0')+'.';else if(cash.length<10)cash+=b.dataset.value;document.querySelector('#cash').value=cash;updateCash();return;}
 if(a==='pay'){const result=validate(cash,total(cart));if(result.error){updateCash(true);document.querySelector('#cash').focus();return;}simulate('Cash',result.paid);return;}
 if(a==='confirm'){simulate('QR Payment',total(cart));return;}
 if(a==='process'){simulate('Credit / Debit Card',total(cart));return;}
 if(a==='reset'){cart={};cash='';transaction=null;category='All';busy=false;go('order');notify('New transaction started — previous order cleared');return;}
 if(a==='print'){window.print();return;}
 if(a==='methods')cash='';go(a);
});
render();
