'use strict';
const {products,money,lines,total,amount,validate,change}=POS;
let cart={},screen='order',category='All',cash='',transaction=null,busy=false,noticeTimer;
const app=document.querySelector('#app');
const paths={coffee:'M16 23h27v20a12 12 0 0 1-12 12h-3a12 12 0 0 1-12-12z M43 27h5a7 7 0 0 1 0 14h-5 M25 10v7 M34 10v7',sandwich:'M9 46 32 15 55 46v9H9z M15 39h34 M9 46h46',soda:'M18 26h30l-4 31H22z M32 26l7-17h9 M20 37h26',cookies:'M55 33a23 23 0 1 1-46 0 23 23 0 0 1 46 0 M23 25h1 M39 22h1 M29 39h1 M43 40h1 M20 43h1',water:'M27 8h10v9l6 9v29a5 5 0 0 1-5 5H26a5 5 0 0 1-5-5V26l6-9z M22 35h20 M22 46h20',chocolate:'M20 9h24a5 5 0 0 1 5 5v41a5 5 0 0 1-5 5H20a5 5 0 0 1-5-5V14a5 5 0 0 1 5-5 M32 10v49 M16 26h32 M16 43h32',cash:'M8 18h48v30H8z M39 33a7 7 0 1 1-14 0 7 7 0 0 1 14 0',qr:'M9 9h17v17H9z M38 9h17v17H38z M9 38h17v17H9z M38 38h8v8h9v9H38z',card:'M8 15h48v36H8z M8 25h48 M16 40h10',bag:'M15 20h34l4 37H11z M24 20v-6a8 8 0 0 1 16 0v6'};
function icon(id){return `<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[id]||paths.bag}"/></svg>`;}
function button(label,action,cls='',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function notify(message){clearTimeout(noticeTimer);document.querySelector('#notice').textContent=message;noticeTimer=setTimeout(()=>document.querySelector('#notice').textContent='',3200);}
function go(next){if(busy)return;if(!total(cart)&&!['order','receipt','success'].includes(next))return;screen=next;render();window.scrollTo(0,0);app.querySelector('h1')?.focus({preventScroll:true});}
function orderTable(items){return `<div class="table-wrap"><table><thead><tr><th>Product</th><th>Quantity</th><th>Unit price</th><th>Subtotal</th></tr></thead><tbody>${items.map(p=>`<tr><td>${p.name}</td><td>${p.quantity}</td><td>${money(p.price)}</td><td>${money(p.subtotal)}</td></tr>`).join('')}</tbody></table></div>`;}
function details(t){return `<dl><div><dt>Transaction No.</dt><dd class="reference">${t.id}</dd></div><div><dt>Payment method</dt><dd>${t.method}</dd></div><div><dt>Transaction amount</dt><dd>${money(t.total)}</dd></div><div><dt>Amount paid</dt><dd>${money(t.paid)}</dd></div><div><dt>Change</dt><dd>${money(t.change)}</dd></div></dl>`;}
function render(){
 const items=lines(cart),due=total(cart),count=items.reduce((n,p)=>n+p.quantity,0),step=screen==='order'?0:screen==='review'?1:['success','receipt'].includes(screen)?3:2;
 document.querySelector('#progress').innerHTML=['Order','Review','Payment','Receipt'].map((s,i)=>`<span class="${i===step?'active':i<step?'done':''}" ${i===step?'aria-current="step"':''}>${i<step?'✓':i+1} ${s}</span>`).join('');
 if(screen==='order')app.innerHTML=`<div class="order-layout"><section class="catalog"><div class="catalog-head"><div class="intro"><span class="eyebrow">THE CAMPUS EDIT</span><h1 tabindex="-1">A little break.<br>A lot to love.</h1><p>Your everyday favorites, just a tap away.</p></div><div class="filters" aria-label="Product categories">${['All','Drinks','Food','Snacks'].map(c=>button(c,'filter',category===c?'selected':'',`data-category="${c}" aria-pressed="${category===c}"`)).join('')}</div></div><div class="menu-heading"><h2>Find your favorite</h2><span>Made for your study break</span></div><div class="products">${products.filter(p=>category==='All'||p.category===category).map(p=>`<button class="product ${p.id} ${cart[p.id]?'chosen':''}" data-action="add" data-id="${p.id}" aria-label="Add ${p.name}, ${money(p.price)}">${cart[p.id]?`<span class="badge">${cart[p.id]}</span>`:''}<div class="art"><span class="art-orbit"></span>${icon(p.id)}<span class="add-mark" aria-hidden="true">+</span></div><div class="product-meta"><div><small class="product-category">${p.category}</small><strong>${p.name}</strong></div><strong class="price">${money(p.price)}</strong></div></button>`).join('')}</div></section><aside class="cart"><div class="row"><h2>Your bag<span class="heading-dot">.</span></h2><span class="muted">${count} items</span></div><div class="cart-items">${items.length?items.map(p=>`<div class="cart-item"><div class="row"><div><strong>${p.name}</strong><small>${money(p.price)} each</small></div>${button('Remove','remove','remove',`data-id="${p.id}" aria-label="Remove ${p.name}"`)}</div><div class="qty">${button('−','minus','',`data-id="${p.id}" aria-label="Decrease ${p.name}"`)}<strong>${p.quantity}</strong>${button('+','add','',`data-id="${p.id}" aria-label="Increase ${p.name}"`)}<strong class="subtotal">${money(p.subtotal)}</strong></div></div>`).join(''):`<div class="empty">${icon('bag')}<h3>Your order is empty</h3><p>Good things start with a little something. Tap a favorite to get started.</p></div>`}</div><div class="row total"><span>Total</span><strong data-testid="total">${money(due)}</strong></div>${button('Review your order ↗','review','primary wide',!items.length?'disabled':'')}</aside></div>`;
 if(screen==='review')app.innerHTML=`<section class="panel"><h1 tabindex="-1">Review your order</h1><p>Check your items before paying. Tap Back to make changes — your items stay in the cart.</p>${orderTable(items)}<div class="total row"><div>Total Amount<small class="muted" style="display:block;font-size:15px;margin-top:8px">${count} items</small></div><strong>${money(due)}</strong></div><div class="actions">${button('← Back','order')}${button('Continue to Payment →','methods','primary')}</div></section>`;
 if(screen==='methods')app.innerHTML=`<section class="panel"><h1 tabindex="-1">How would you like to pay?</h1><p>Tap one of the options below.</p><div class="due"><small>Amount due</small><strong>${money(due)}</strong></div><div class="methods">${[['cash','Cash','Enter the amount you are paying. Change is computed for you.'],['qr','QR Payment','Simulate a payment with an e-wallet or banking app.'],['card','Credit / Debit Card','Simulate tapping, inserting, or swiping a card.']].map(([id,title,desc])=>`<button class="method" data-action="${id}">${icon(id)}<strong>${title}</strong><p>${desc}</p></button>`).join('')}</div><div class="actions">${button('← Back to Order','order')}</div><p class="simulation">Demonstration kiosk · No real payment is collected.</p></section>`;
 if(screen==='cash'){app.innerHTML=`<section class="panel narrow"><h1 tabindex="-1">Cash Payment</h1><div class="total row"><span>Total amount</span><strong>${money(due)}</strong></div><label for="cash">Amount paid</label><input id="cash" class="cash-input" inputmode="decimal" autocomplete="off" placeholder="₱0.00" aria-describedby="cash-error" maxlength="10"><p id="cash-error" class="error" role="alert"></p><div class="quick">${[['Exact',due/100],['₱200',200],['₱500',500],['₱1,000',1000]].map(([s,v])=>button(s,'quick','',`data-value="${v}"`)).join('')}</div><div class="change row"><span>Change</span><strong id="change">—</strong></div><div class="keypad">${['1','2','3','4','5','6','7','8','9','.','0','⌫'].map(n=>button(n,'key','',`data-value="${n}" aria-label="${n==='⌫'?'Backspace':n==='.'?'Decimal point':n}"`)).join('')}</div>${button('Clear','clear','wide')}<div class="actions">${button('Pay Now','pay','primary')}</div><div class="actions">${button('Change payment method','methods')}</div></section>`;document.querySelector('#cash').value=cash;updateCash();}
 if(screen==='qr')app.innerHTML=`<section class="panel narrow"><h1 tabindex="-1">QR Payment</h1><div class="qr">QR CODE<br>placeholder</div><div class="due"><small>Amount to pay</small><strong>${money(due)}</strong></div><p>1. Scan the QR code using your supported payment application.<br>2. Check the amount and approve it in your app.<br>3. Tap Confirm Payment below.</p><p class="simulation">This placeholder is for demonstration only. Confirm Payment simulates approval with zero change.</p><div class="actions">${button('Back','methods')}${button('Confirm Payment','confirm','primary')}</div></section>`;
 if(screen==='card')app.innerHTML=`<section class="panel narrow"><h1 tabindex="-1">Credit / Debit Card</h1><div class="due">${icon('card')}<small>Amount due</small><strong>${money(due)}</strong></div><p>Please tap, insert, or swipe your card.</p>${busy?'<div class="spinner"></div><p role="status" style="text-align:center">Processing payment…<br>Do not remove your card until payment is complete.</p>':''}<p class="simulation">Simulated payment · No card details required.</p><div class="actions">${button('Back','methods','',busy?'disabled':'')}${button(busy?'Processing…':'Process Payment','process','primary',busy?'disabled':'')}</div></section>`;
 if(screen==='success')app.innerHTML=`<section class="panel narrow success"><div class="check">✓</div><h1 tabindex="-1">Payment Successful</h1><p>Transaction completed successfully. Thank you!</p>${details(transaction)}${button('View Receipt','receipt','primary wide')}</section>`;
 if(screen==='receipt'){const t=transaction;app.innerHTML=`<div class="receipt-layout"><section class="receipt"><h2>CAMPUS STORE POS</h2><p>Self-Service Kiosk · Digital Receipt</p><dl><div><dt>Transaction No.</dt><dd class="reference">${t.id}</dd></div><div><dt>Date</dt><dd>${new Intl.DateTimeFormat('en-PH',{dateStyle:'long',timeStyle:'short',timeZone:'Asia/Manila'}).format(new Date(t.date))} (PHT)</dd></div></dl><table><thead><tr><th>Item</th><th>Subtotal</th></tr></thead><tbody>${t.items.map(p=>`<tr><td>${p.name}<small>${p.quantity} × ${money(p.price)}</small></td><td>${money(p.subtotal)}</td></tr>`).join('')}</tbody></table><div class="total row"><span>TOTAL</span><strong>${money(t.total)}</strong></div><dl><div><dt>Payment method</dt><dd>${t.method}</dd></div><div><dt>Amount paid</dt><dd>${money(t.paid)}</dd></div><div><dt>Change</dt><dd>${money(t.change)}</dd></div><div><dt>Status</dt><dd>Payment Successful</dd></div></dl><p>Thank you for your purchase!</p></section><section class="receipt-actions"><h1 tabindex="-1">Your receipt</h1><p>Keep this for your records. Tap New Transaction when you are done — your order and payment details will be cleared.</p>${button('New Transaction','reset','primary')}${button('Print Receipt','print')}<p class="simulation">Printing is optional. Payments in this kiosk are simulated.</p></section></div>`;}
}
function updateCash(){const field=document.querySelector('#cash');if(!field)return;const paid=amount(cash);document.querySelector('#change').textContent=paid!==null&&paid>=total(cart)?money(paid-total(cart)):'—';document.querySelector('#cash-error').textContent='';field.removeAttribute('aria-invalid');}
function complete(method,paid){if(transaction||!total(cart))return;transaction={id:'TXN-'+crypto.randomUUID().toUpperCase(),date:new Date().toISOString(),items:lines(cart),total:total(cart),method,paid,change:paid-total(cart)};busy=false;go('success');notify('Transaction completed successfully');}
app.addEventListener('input',e=>{if(e.target.id==='cash'){cash=e.target.value;updateCash();}});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||busy)return;const a=b.dataset.action,id=b.dataset.id;
 if(['add','minus','remove'].includes(a)){const p=products.find(p=>p.id===id);if(a==='remove'){delete cart[id];notify(`${p.name} removed`);}else{if(a==='add'&&cart[id]>=99){notify('Maximum quantity is 99 per product');return;}cart=change(cart,id,a==='add'?1:-1);notify(a==='add'?`Product added — ${p.name}`:`Quantity updated — ${p.name}`);}render();const target=[...app.querySelectorAll('button')].find(n=>n.dataset.action===a&&n.dataset.id===id);target?.focus({preventScroll:true});return;}
 if(a==='filter'){category=b.dataset.category;render();return;}
 if(['quick','key','clear'].includes(a)){if(a==='quick')cash=b.dataset.value;else if(a==='clear')cash='';else if(b.dataset.value==='⌫')cash=cash.slice(0,-1);else if(b.dataset.value==='.')cash=cash.includes('.')?cash:(cash||'0')+'.';else if(cash.length<10)cash+=b.dataset.value;document.querySelector('#cash').value=cash;updateCash();return;}
 if(a==='pay'){const result=validate(cash,total(cart));if(result.error){document.querySelector('#cash-error').textContent=result.error;document.querySelector('#cash').setAttribute('aria-invalid','true');return;}complete('Cash',result.paid);return;}
 if(a==='confirm'){complete('QR Payment',total(cart));return;}
 if(a==='process'){busy=true;render();setTimeout(()=>complete('Credit / Debit Card',total(cart)),1400);return;}
 if(a==='reset'){cart={};cash='';transaction=null;category='All';busy=false;go('order');notify('New transaction started — previous order cleared');return;}
 if(a==='print'){window.print();return;}
 if(a==='methods')cash='';go(a);
});
render();
